<?xml version="1.0"?>
<package format="3">
  <name>mapf_ros</name>
  <version>0.0.0</version>
  <description>The mapf algorithm package</description>

  <maintainer email="speed@mail.ustc.edu.cn">speed</maintainer>

  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>std_msgs</depend>
  <depend>visualization_msgs</depend>
  
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav2_util</depend>
  <depend>builtin_interfaces</depend>

  <depend>tf2_ros</depend>
  <depend>nav2_costmap_2d</depend>

  <depend>pluginlib</depend>
  <depend>mapf_msgs</depend>

  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <!-- The export tag contains other, unspecified, tags -->
  <export>
    <build_type>ament_cmake</build_type>
    <mapf_ros plugin="${prefix}/cbs_planner_plugins.xml" />
    <mapf_ros plugin="${prefix}/ecbs_planner_plugins.xml" />
    <mapf_ros plugin="${prefix}/sipp_planner_plugins.xml" />
  </export>

</package>